name: Docker Image CI

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout1
        run:  echo "Checkout1 done"

      - uses: nelonoel/branch-name@v1
      - name: Get branch name
      # Use Docker `latest` tag convention
        run:  |
              echo "::set-env name=FINAL_BRANCH_NAME::`sed 's/master/latest/g' <<< $BRANCH_NAME`"
              unset BRANCH_NAME

      - name: Print branch name
        run:  echo "FINAL_BRANCH_NAME = $FINAL_BRANCH_NAME"

      - name: Build the Docker image
        run:  docker build . --file Dockerfile --tag ap42/alpine-tidyhtml:$FINAL_BRANCH_NAME

      - name: Publish the image to GitHub Packages
        run:  docker push docker.pkg.github.com/ap42/alpine-tidyhtml:$FINAL_BRANCH_NAME

  test:

    needs: build
    runs-on: ubuntu-latest

    steps:
      - id:   Pull-image
      - name: Pull Docker image
        run:  docker pull docker.pkg.github.com/ap42/alpine-tidyhtml:$FINAL_BRANCH_NAME

      - id:   Test-Docker-image
      - name: Test Docker image
        run: |

          docker run -ti -d --rm --name atidy ap42/alpine-tidyhtml:$FINAL_BRANCH_NAME sh
          # Validate that `tidy` is accessible
          docker exec atidy which tidy
          if [ $? -ne 0 ]; then exit 1; fi
