name: CI

# Trigger the workflow on push
on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout1
        run:  echo "Checkout1 done"

      - uses: nelonoel/branch-name@v1
      - name: Get branch name
      # Use Docker `latest` tag convention
        run:  |
              echo "name=FINAL_BRANCH_NAME::`sed 's/master/latest/g' <<< $BRANCH_NAME`" >> $GITHUB_ENV
              unset BRANCH_NAME

      - name: Print branch name
        run:  echo "FINAL_BRANCH_NAME = ${{ env.name }}"

      - name: Build the Docker image
        run:  docker build . --file Dockerfile --tag ap42/alpine-tidyhtml:${{ env.name }}

      # test: TODO use GitHub Packages to share image between jobs

      - name: Test Docker image
        run: |
             docker run -ti -d --rm --name atidy ap42/alpine-tidyhtml:${{ env.name }} sh
             # Validate that `tidy` is accessible
             docker exec atidy which tidy
             if [ $? -ne 0 ]; then exit 1; fi
